#########
#GENERAL#
#########

#Language files can be found at the plugin's website, to use a different language, download the desired file and put it in the plugin data folder!
languageFile: "plugin_msgs_en.yml"
#Writes new placed item location data to a file every x minutes
useLocationAutoSave: true
#Will automatically use lists starting with the name 'legacy' if a legacy server version is detected
#I recomend keeping this set to true
forceLegacy: true
#Time is in minutes for autosave
locationAutoSaveTime: 1
#Repeat the update checker every hour (true) or only on server boot (false)
repeatUpdateChecker: true
#Default amount of items a player can place on the ground (set to -1 for unlimited)
defaultPlaceCap: 10
#Allow item placing on the top of blocks
allowTopPlacing: true
#Allow item placing on the sides of blocks
allowSidePlacing: true
#Allow item placing on the bottom of blocks
allowBottomPlacing: true
#This plugin now uses bStats! This helps me collect some basic information on how and where this plugin in being used.
#You can read about this here: https://bstats.org
#I would really appriciate it if you left this set to true! <3
bStats: true
#Prevent items from being placed on the gound in certain worlds.
#Example: worldBlacklist: world1, world2
worldBlacklist:

#######################
#EXPERIMENTAL FEATURES#
#######################

#/plot clear and /plot delete will remove any placed items correctly
plotSquaredClear: false

#This is designed to resolve issues with "custom item" or "custom block" plugins.
#Making this setting this to true will make it so that only blocks or items can be placed that do not have a display name or lore.
strictCompatibilityMode: false

###################
#BLACKLISTED ITEMS#
###################

#HOW TO CHANGE A LIST:
#Add items to this list using ", TYPE" without quotes. Make sure all items on the list are on the same line. Here is a link to all item type names: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
#Note that if there are any items on here that are not in the current version of the server you are running, they will just be ignored.
#The lists that do not start with legacy have all items from 1.13 to 1.14. Lists that start with legacy will be used for versions older than 1.13

#This is a list of items that being placed on the groud has been disabled for with using this plugin.
#The current items here are all items that have unconvential displays on armor stand heads and don't play nicely with the plugin so I would not recomend removing any of these.
blacklistedItemsAll: WHITE_BED, ORANGE_BED, MAGENTA_BED, LIGHT_BLUE_BED, YELLOW_BED,
  LIME_BED, PINK_BED, GRAY_BED, LIGHT_GRAY_BED, CYAN_BED, PURPLE_BED, BLUE_BED, BROWN_BED,
  GREEN_BED, RED_BED, BLACK_BED, WHITE_BANNER, ORANGE_BANNER, MAGENTA_BANNER, LIGHT_BLUE_BANNER,
  YELLOW_BANNER, LIME_BANNER, PINK_BANNER, GRAY_BANNER, LIGHT_GRAY_BANNER, CYAN_BANNER,
  PURPLE_BANNER, BLUE_BANNER, BROWN_BANNER, GREEN_BANNER, RED_BANNER, BLACK_BANNER,
  TRIDENT, SHIELD

blacklistedItemsTop:

blacklistedItemsSides: END_ROD, LEAD, BONE

blacklistedItemsBottom: OAK_SLAB, SPRUCE_SLAB, BIRCH_SLAB, JUNGLE_SLAB,
  ACACIA_SLAB, DARK_OAK_SLAB, STONE_SLAB, SMOOTH_STONE_SLAB, SANDSTONE_SLAB, CUT_SANDSTONE_SLAB,
  PETRIFIED_OAK_SLAB, COBBLESTONE_SLAB, BRICK_SLAB, STONE_BRICK_SLAB, NETHER_BRICK_SLAB,
  QUARTZ_SLAB, RED_SANDSTONE_SLAB, CUT_RED_SANDSTONE_SLAB, PURPUR_SLAB, PRISMARINE_SLAB,
  PRISMARINE_BRICK_SLAB, DARK_PRISMARINE_SLAB, POLISHED_GRANITE_SLAB, SMOOTH_RED_SANDSTONE_SLAB,
  MOSSY_STONE_BRICK_SLAB, POLISHED_DIORITE_SLAB, MOSSY_COBBLESTONE_SLAB, END_STONE_BRICK_SLAB,
  SMOOTH_SANDSTONE_SLAB, SMOOTH_QUARTZ_SLAB, GRANITE_SLAB, ANDESITE_SLAB, RED_NETHER_BRICK_SLAB,
  POLISHED_ANDESITE_SLAB, DIORITE_SLAB, STONE_PRESSURE_PLATE, OAK_PRESSURE_PLATE, SPRUCE_PRESSURE_PLATE,
  BIRCH_PRESSURE_PLATE, JUNGLE_PRESSURE_PLATE, ACACIA_PRESSURE_PLATE, DARK_OAK_PRESSURE_PLATE,
  LIGHT_WEIGHTED_PRESSURE_PLATE, HEAVY_WEIGHTED_PRESSURE_PLATE, END_ROD

legacyBlacklistedItemsAll: BED, SHIELD, BANNER

legacyBlacklistedItemsTop:

legacyBlacklistedItemsSides: END_ROD, LEASH, BONE

legacyBlacklistedItemsBottom: PURPUR_SLAB, WOOD_STEP, STEP, STONE_SLAB2,
  GOLD_PLATE, WOOD_PLATE, IRON_PLATE, STONE_PLATE, END_ROD

#################
#DO NOT PLACE ON#
#################

#This is a list of blocks that items cannot be placed on.
#The current items here are all blocks that don't look right when an item is placed on them. I don't recomend removing any of these.
blacklistedPlaceItemsAll: IRON_DOOR, OAK_DOOR, SPRUCE_DOOR, JUNGLE_DOOR, ACACIA_DOOR,
  DARK_OAK_DOOR, BIRCH_DOOR, OAK_TRAPDOOR, SPRUCE_TRAPDOOR, BIRCH_TRAPDOOR, JUNGLE_TRAPDOOR,
  ACACIA_TRAPDOOR, DARK_OAK_TRAPDOOR, IRON_TRAPDOOR, WHITE_BED, ORANGE_BED,
  MAGENTA_BED, LIGHT_BLUE_BED, YELLOW_BED, LIME_BED, PINK_BED, GRAY_BED, LIGHT_GRAY_BED,
  CYAN_BED, PURPLE_BED, BLUE_BED, BROWN_BED, GREEN_BED, RED_BED, BLACK_BED, WHITE_BANNER,
  ORANGE_BANNER, MAGENTA_BANNER, LIGHT_BLUE_BANNER, YELLOW_BANNER, LIME_BANNER, PINK_BANNER,
  GRAY_BANNER, LIGHT_GRAY_BANNER, CYAN_BANNER, PURPLE_BANNER, BLUE_BANNER, BROWN_BANNER,
  GREEN_BANNER, RED_BANNER, BLACK_BANNER, COBBLESTONE_WALL, MOSSY_COBBLESTONE_WALL,
  BRICK_WALL, PRISMARINE_WALL, RED_SANDSTONE_WALL, MOSSY_STONE_BRICK_WALL, GRANITE_WALL,
  STONE_BRICK_WALL, NETHER_BRICK_WALL, ANDESITE_WALL, RED_NETHER_BRICK_WALL, SANDSTONE_WALL,
  END_STONE_BRICK_WALL, DIORITE_WALL, STONE_PRESSURE_PLATE, OAK_PRESSURE_PLATE, SPRUCE_PRESSURE_PLATE,
  BIRCH_PRESSURE_PLATE, JUNGLE_PRESSURE_PLATE, ACACIA_PRESSURE_PLATE, DARK_OAK_PRESSURE_PLATE,
  LIGHT_WEIGHTED_PRESSURE_PLATE, HEAVY_WEIGHTED_PRESSURE_PLATE, END_PORTAL_FRAME, CAKE, HOPPER, BREWING_STAND,
  TURTLE_EGG, BELL, CAMPFIRE, DAYLIGHT_DETECTOR, WHITE_SHULKER_BOX, ORANGE_SHULKER_BOX, MAGENTA_SHULKER_BOX, LIGHT_BLUE_SHULKER_BOX,
  YELLOW_SHULKER_BOX, LIME_SHULKER_BOX, PINK_SHULKER_BOX, GRAY_SHULKER_BOX, LIGHT_GRAY_SHULKER_BOX, CYAN_SHULKER_BOX, PURPLE_SHULKER_BOX,
  BLUE_SHULKER_BOX, BROWN_SHULKER_BOX, GREEN_SHULKER_BOX, RED_SHULKER_BOX, SHULKER_BOX, OAK_FENCE_GATE, SPRUCE_FENCE_GATE,
  BIRCH_FENCE_GATE, JUNGLE_FENCE_GATE, DARK_OAK_FENCE_GATE, ACACIA_FENCE_GATE

blacklistedPlaceItemsTop: ENCHANTING_TABLE, CAULDRON, GRASS_PATH, FARMLAND, LECTERN, STONECUTTER

blacklistedPlaceItemsSides: STONECUTTER, GLASS_PANE, WHITE_STAINED_GLASS_PANE, ORANGE_STAINED_GLASS_PANE,
  MAGENTA_STAINED_GLASS_PANE, LIGHT_BLUE_STAINED_GLASS_PANE, YELLOW_STAINED_GLASS_PANE,
  LIME_STAINED_GLASS_PANE, PINK_STAINED_GLASS_PANE, GRAY_STAINED_GLASS_PANE, LIGHT_GRAY_STAINED_GLASS_PANE,
  CYAN_STAINED_GLASS_PANE, PURPLE_STAINED_GLASS_PANE, BLUE_STAINED_GLASS_PANE, BROWN_STAINED_GLASS_PANE,
  GREEN_STAINED_GLASS_PANE, RED_STAINED_GLASS_PANE, BLACK_STAINED_GLASS_PANE, IRON_BARS, LECTERN, GRINDSTONE,
  ANVIL, CHIPPED_ANVIL, DAMAGED_ANVIL, OAK_FENCE, NETHER_BRICK_FENCE, SPRUCE_FENCE, BIRCH_FENCE, JUNGLE_FENCE,
  ACACIA_FENCE, DARK_OAK_FENCE

blacklistedPlaceItemsBottom: CAULDRON, GRINDSTONE

legacyBlacklistedPlaceItemsAll: IRON_DOOR_BLOCK, WOODEN_DOOR, SPRUCE_DOOR, JUNGLE_DOOR, ACACIA_DOOR,
  DARK_OAK_DOOR, BIRCH_DOOR, IRON_TRAPDOOR, TRAP_DOOR, BED_BLOCK, STANDING_BANNER, WALL_BANNER,
  COBBLE_WALL, GOLD_PLATE, WOOD_PLATE, IRON_PLATE, STONE_PLATE, HOPPER, CAKE_BLOCK, ENDER_PORTAL_FRAME,
  DAYLIGHT_DETECTOR, WHITE_SHULKER_BOX, ORANGE_SHULKER_BOX, MAGENTA_SHULKER_BOX, LIGHT_BLUE_SHULKER_BOX,
  YELLOW_SHULKER_BOX, LIME_SHULKER_BOX, PINK_SHULKER_BOX, GRAY_SHULKER_BOX, LIGHT_GRAY_SHULKER_BOX, CYAN_SHULKER_BOX, PURPLE_SHULKER_BOX,
  BLUE_SHULKER_BOX, BROWN_SHULKER_BOX, GREEN_SHULKER_BOX, RED_SHULKER_BOX, PURPLE_SHULKER_BOX, SHULKER_BOX, FENCE_GATE, SPRUCE_FENCE_GATE,
  BIRCH_FENCE_GATE, JUNGLE_FENCE_GATE, DARK_OAK_FENCE_GATE, ACACIA_FENCE_GATE

legacyBlacklistedPlaceItemsTop: ENCHANTING_TABLE, CAULDRON, GRASS_PATH, SOIL

legacyBlacklistedPlaceItemsSides: IRON_FENCE, THIN_GLASS, STAINED_GLASS_PANE, ANVIL, FENCE, NETHER_FENCE,
  SPRUCE_FENCE, BIRCH_FENCE, JUNGLE_FENCE, ACACIA_FENCE, DARK_OAK_FENCE

legacyBlacklistedPlaceItemsBottom: CAULDRON

###################
#USEFUL ITEM LISTS#
###################

#This is a list of all items in the game that can move (ex: sand can fall) or dissappear (ex: tnt can explode) on their own
#Set this to true to disable placing items on these kinds of blocks
includeBlocksThatCanMoveOrDisappear: false
blocksThatCanMoveOrDisappear: ACACIA_LEAVES, BIRCH_LEAVES, OAK_LEAVES, SPRUCE_LEAVES, DARK_OAK_LEAVES, JUNGLE_LEAVES, GRAVEL, SAND, PISTON,
  STICKY_PISTON, RED_SAND, ICE, TNT, WHITE_CONCRETE_POWDER, ORANGE_CONCRETE_POWDER, MAGENTA_CONCRETE_POWDER, LIGHT_BLUE_CONCRETE_POWDER, YELLOW_CONCRETE_POWDER,
  LIME_CONCRETE_POWDER, PINK_CONCRETE_POWDER, GRAY_CONCRETE_POWDER, LIGHT_GRAY_CONCRETE_POWDER, CYAN_CONCRETE_POWDER, PURPLE_CONCRETE_POWDER,
  BLUE_CONCRETE_POWDER, BROWN_CONCRETE_POWDER, GREEN_CONCRETE_POWDER, RED_CONCRETE_POWDER, ANVIL, CHIPPED_ANVIL, DAMAGED_ANVIL

legacyBlocksThatCanMoveOrDisappear: LEAVES, SAND, GRAVEL, PISTON_STICKY_BASE, PISTON_BASE, ICE, TNT, CONCRETE_POWDER, ANVIL

#This a list of all slabs in the game, if you want to include them in the blacklist just copy and paste them
slabs: OAK_SLAB, SPRUCE_SLAB, BIRCH_SLAB, JUNGLE_SLAB,
  ACACIA_SLAB, DARK_OAK_SLAB, STONE_SLAB, SMOOTH_STONE_SLAB, SANDSTONE_SLAB, CUT_SANDSTONE_SLAB,
  PETRIFIED_OAK_SLAB, COBBLESTONE_SLAB, BRICK_SLAB, STONE_BRICK_SLAB, NETHER_BRICK_SLAB,
  QUARTZ_SLAB, RED_SANDSTONE_SLAB, CUT_RED_SANDSTONE_SLAB, PURPUR_SLAB, PRISMARINE_SLAB,
  PRISMARINE_BRICK_SLAB, DARK_PRISMARINE_SLAB, POLISHED_GRANITE_SLAB, SMOOTH_RED_SANDSTONE_SLAB,
  MOSSY_STONE_BRICK_SLAB, POLISHED_DIORITE_SLAB, MOSSY_COBBLESTONE_SLAB, END_STONE_BRICK_SLAB,
  SMOOTH_SANDSTONE_SLAB, SMOOTH_QUARTZ_SLAB, GRANITE_SLAB, ANDESITE_SLAB, RED_NETHER_BRICK_SLAB,
  POLISHED_ANDESITE_SLAB, DIORITE_SLAB

legacySlabs: PURPUR_SLAB, WOOD_STEP, STEP, STONE_SLAB2

legacyDoubleSlabs: PURPUR_DOUBLE_SLAB, DOUBLE_STONE_SLAB2, WOOD_DOUBLE_STEP, DOUBLE_STEP

#This a list of all slabs in the game, if you want to include them in the blacklist just copy and paste them
stairs: OAK_STAIRS, SPRUCE_STAIRS, BIRCH_STAIRS, JUNGLE_STAIRS,
  ACACIA_STAIRS, DARK_OAK_STAIRS, STONE_STAIRS, SANDSTONE_STAIRS, COBBLESTONE_STAIRS,
  BRICK_STAIRS, STONE_BRICK_STAIRS, NETHER_BRICK_STAIRS, QUARTZ_STAIRS, RED_SANDSTONE_STAIRS,
  PURPUR_STAIRS, PRISMARINE_STAIRS, PRISMARINE_BRICK_STAIRS, DARK_PRISMARINE_STAIRS,
  POLISHED_GRANITE_STAIRS, SMOOTH_RED_SANDSTONE_STAIRS, MOSSY_STONE_BRICK_STAIRS,
  POLISHED_DIORITE_STAIRS, MOSSY_COBBLESTONE_STAIRS, END_STONE_BRICK_STAIRS, SMOOTH_SANDSTONE_STAIRS,
  SMOOTH_QUARTZ_STAIRS, GRANITE_STAIRS, ANDESITE_STAIRS, RED_NETHER_BRICK_STAIRS,
  POLISHED_ANDESITE_STAIRS, DIORITE_STAIRS

legacyStairs: WOOD_STAIRS, SPRUCE_WOOD_STAIRS, BIRCH_WOOD_STAIRS, JUNGLE_WOOD_STAIRS,
  ACACIA_STAIRS, DARK_OAK_STAIRS, STONE_STAIRS, SANDSTONE_STAIRS, COBBLESTONE_STAIRS,
  BRICK_STAIRS, SMOOTH_STAIRS, NETHER_BRICK_STAIRS, QUARTZ_STAIRS, PURPUR_STAIRS

###############
#SPECIAL CASES#
###############

#There are some items in the game that behave like blocks when put on an armor stand head and some blocks that behave like items when put on an armor stand head!

#If an item is sticking straight up when it is placed, adding it to this list should fix that
itemLikeBlocks: BARRIER, TRIPWIRE_HOOK, DEAD_BUSH, BROWN_MUSHROOM, RED_MUSHROOM, LADDER,
  TORCH, LEVER, RAIL, ACTIVATOR_RAIL, DETECTOR_RAIL, POWERED_RAIL, LADDER, VINE,
  HOPPER, SEA_PICKLE, IRON_DOOR, OAK_DOOR, SPRUCE_DOOR, BIRCH_DOOR, JUNGLE_DOOR, ACACIA_DOOR,
  DARK_OAK_DOOR, REDSTONE_TORCH, COMPARATOR, REPEATER, IRON_BARS, DEAD_HORN_CORAL,
  DEAD_FIRE_CORAL, DEAD_BUBBLE_CORAL, DEAD_BRAIN_CORAL, HORN_CORAL, FIRE_CORAL, BUBBLE_CORAL,
  BRAIN_CORAL, TUBE_CORAL, FIRE_CORAL_FAN, HORN_CORAL_FAN, DEAD_BRAIN_CORAL_FAN, DEAD_BUBBLE_CORAL_FAN,
  DEAD_FIRE_CORAL_FAN, DEAD_HORN_CORAL_FAN, DEAD_TUBE_CORAL_FAN, TUBE_CORAL_FAN, DEAD_TUBE_CORAL,
  BRAIN_CORAL_FAN, BUBBLE_CORAL_FAN, PEONY, PINK_TULIP, WHITE_TULIP, ORANGE_TULIP,
  RED_TULIP, SEAGRASS, OXEYE_DAISY, BLUE_ORCHID, GRASS, ROSE_BUSH, SUNFLOWER, AZURE_BLUET,
  POPPY, DANDELION, ALLIUM, LILAC, LARGE_FERN, TALL_GRASS, LILY_OF_THE_VALLEY, CORNFLOWER,
  FERN, OAK_SAPLING, DARK_OAK_SAPLING, BIRCH_SAPLING, SPRUCE_SAPLING, ACACIA_SAPLING,
  JUNGLE_SAPLING, BAMBOO, LILY_PAD, WITHER_ROSE, CAULDRON, BREWING_STAND, TURTLE_EGG,
  FLOWER_POT, BELL, CAMPFIRE, LANTERN, COBWEB, CAKE, OAK_SIGN, SPRUCE_SIGN, BIRCH_SIGN,
  JUNGLE_SIGN, ACACIA_SIGN, DARK_OAK_SIGN, GLASS_PANE, WHITE_STAINED_GLASS_PANE, ORANGE_STAINED_GLASS_PANE,
  MAGENTA_STAINED_GLASS_PANE, LIGHT_BLUE_STAINED_GLASS_PANE, YELLOW_STAINED_GLASS_PANE,
  LIME_STAINED_GLASS_PANE, PINK_STAINED_GLASS_PANE, GRAY_STAINED_GLASS_PANE, LIGHT_GRAY_STAINED_GLASS_PANE,
  CYAN_STAINED_GLASS_PANE, PURPLE_STAINED_GLASS_PANE, BLUE_STAINED_GLASS_PANE, BROWN_STAINED_GLASS_PANE,
  GREEN_STAINED_GLASS_PANE, RED_STAINED_GLASS_PANE, BLACK_STAINED_GLASS_PANE, SIGN, NETHER_WART

legacyItemLikeBlocks: BARRIER, TRIPWIRE_HOOK, DEAD_BUSH, BROWN_MUSHROOM, RED_MUSHROOM, LADDER,
  TORCH, LEVER, RAILS, ACTIVATOR_RAIL, DETECTOR_RAIL, POWERED_RAIL, LADDER, VINE,
  HOPPER, IRON_FENCE, REDSTONE_TORCH_ON, YELLOW_FLOWER, RED_FLOWER, SAPLING, DOUBLE_PLANT, SIGN,
  THIN_GLASS, WEB, STAINED_GLASS_PANE, NETHER_WART

#If an item is clipping into the groud funny adding it here might fix it, if not it might need to be blacklisted
blockLikeItems: LEATHER_HELMET, CHAINMAIL_HELMET, GOLD_HELMET, IRON_HELMET, DIAMOND_HELMET,
  TURTLE_HELMET

legacyBlockLikeItems: LEATHER_HELMET, CHAINMAIL_HELMET, GOLD_HELMET, IRON_HELMET, DIAMOND_HELMET,
  TURTLE_HELMET, SKULL_ITEM

##########
#PLACE IN#
##########

#Blocks the user can place items in (blocks above the one clicked)
placeIn: AIR, CAVE_AIR, WATER

##############
#DO NOT TOUCH#
##############
configVersion: 9
